@startuml teste 
class Lutador{
    - String: nome
    - String: nacionalidade
    - int: idade
    - float: peso
    - float: altura
    - String: categoria
    - int: vitorias
    - int: derrotas
    - int: empates

    + status()
    + ganlharLuta()
    + perderLuta()
    + empatarLuta()


    + getNome()
    + setNome()
    + getNacionalidade()
    + getIdade()
    + setIdade()
    + getPeso()
    + setPeso()
    + getaAtura()
    + setaAtura()
    + getCategoria()
    + setCategoria()
    + getVitorias()
    + setVitorias()
    + getDerrotas()
    + setDerrotas()
    + getEmpates()
    + setEmpates()
    
}
class Luta{
    - Lutador: desafiante
    - Lutador: desafiado
    - int:     rounds
    - boolean: aprovada

    + void marcaLuta()
    + void lutar()
}
Evento *-- Luta
Luta o-- Lutador
Enpresa --> Lutador
Enpresa --> Evento
@enduml
